Service:
  RegionId: cn-hangzhou
  OperationMetadata:
    ModifyParametersConfig:
      - TemplateName: '模版1'
        Operation:
          - Name: 修改Helm参数
            Description: 修改Helm参数
            Type: Custom
            SupportPredefinedParameters: false
            EnableLogging: false
            Parameters:
              - ChartValues
  DeployMetadata:
    TemplateConfigs:
      - Name: 模版1
        Url: 'ros_templates/template.yaml'
        AllowedRegions:
          - ap-southeast-1
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: helm chart deploy
    Image: 'resources/icons/service_logo.png'